#!/bin/bash

test -d "$1"

tmp=`mktemp`

SEDSCRIPT=`realpath $0 | xargs dirname`/src2valencia-moz.sed

# recorreguem tots els fitxers ftl i properties
find $1 -name \*.ftl -or -name \*.properties -or -name \*.ini | while read ca
#find /home/pasqual/treball/construccio_paquets_mozilla/l10n-central/tmp -name "newtab.ftl" | while read ca 
do
	# llegim totes les linies del fitxer
	while IFS= read -r str; 
	do
		#utilitzem per trencar les linies el carcter = per separar la etiqueta de la cadena a traduir
		IFS='='
		#trenquem la linia en un array de les peces separades pel IFS
		read -ra ADDR <<< "$str" # str is read into an array as tokens separated by IFS
		count=1
		primera_part=""
		segona_part=""
		#ens anem a quedar amb la primera peça (l'etiqueta) i les restes unides (la cadena a traduir)
		for i in "${ADDR[@]}";
		do # access each element of array
			if [[ $count -eq 1 ]]
			then
				primera_part=$i
			else
				segona_part=$segona_part$i
				if [ $count -lt ${#ADDR[@]} ]
				then
					segona_part="${segona_part}="
				fi
			fi
			count=$(( $count + 1 ))
		done
		#echo primera_part: "${primera_part}"
		#echo segona_part: "${segona_part}"
		#echo 
		if [ -n "$segona_part" ]; then
			segona_part=`echo "msgstr ${segona_part}" | $SEDSCRIPT | cut -c 8-`
			primera_part="${primera_part}=${segona_part}"
		fi
		# si l'ultim caracter de la linia era un = el tornem a ficar
		if [ "${str: -1}" = "=" ]
		then 
			primera_part="${primera_part}="
		fi
		echo "${primera_part}"
		
		IFS=' '
		#echo "Text read from file: $str"
	done < $ca > $tmp
	#echo $ca
	#echo $tmp

	#sobrescrivim el fitxer resultat amb el resultat
	chmod --reference=$ca $tmp
	mv $tmp $ca
done
